### PR TITLE
UI fixes & performance improvements

### PR DESCRIPTION
**Pull request by PegasisForever**
- Made animation in main activity smoother
- Cleaned some code
- Don't show "Rm" when there's no room number
- Fixed text overflow when course don't have average mark
 => 
- Fixed circular progressbar not showing correct percentage
 =>

### CODE REVIEW

**Comment by milbin** [comment]
Ive merged the pull request but im just going to change the "N/A" that shows up when the teacher hides a course back to the "Please See Teacher For Current Mark In This Course" because "N/A" makes the user think that something went wrong in the code. For example when you run `Double.parseDouble()`  on a string then it will return "NA" as a string. If you have a suggestion for something other than "Please See Teacher For Current Mark In This Course" were definitely open to hearing it! Just leave a comment or open another pull request.

**Comment by PegasisForever** [comment]
Good point. I think the best way to do it may be keep the full text but remove the empty ring?

---

> For example when you run Double.parseDouble() on a string then it will return "NA" as a string. 

`Double.parseDouble()` acturally throws an exception when the String is not parsable. 

I think what you mean is `NaN` (not a number)? `N/A` means "not available".

**Comment by milbin** [comment]
Right yes I did mean NaN. Either way in my opinion N/A looks a bit like something went wrong in the code to cause the N/A especially since we've had the "Please see teacher..." for so long and users are somewhat used to it already. I thought I fixed the ring overlap issue in the last update? But I guess not lol. I'll make sure the next one includes a fix.

**Comment by PegasisForever** [comment]
Haha I can check the code later tonight

**Pull request merged**
